# Default values for openmrs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

openmrs-backend:
  db:
    hostname: mariadb-primary

  mariadb:
    enabled: true
    auth:
      rootPassword: Root123
      database: openmrs
      username: openmrs
      password: OpenMRS123
    fullnameOverride: mariadb

