apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmrs-frontend.fullname" . }}
  labels:
    {{- include "openmrs-frontend.labels" . | nindent 4 }}
data:
  SPA_PATH: "/openmrs/spa"
  API_URL: "/openmrs"
  SPA_CONFIG_URLS: "/openmrs/spa/config-core_demo.json"
  SPA_DEFAULT_LOCALE: "en"
