apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openmrs-backend.fullname" . }}
  labels:
    {{- include "openmrs-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMRS_DB_USERNAME: {{ .Values.mariadb.auth.username | quote}}
  OMRS_DB_PASSWORD: {{ .Values.mariadb.auth.password | quote}}